apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-service
  template:
    metadata:
      labels:
        app: echo-service
    spec:
      containers:
      - name: echo
        image: ealen/echo-server:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
  namespace: default
spec:
  selector:
    app: echo-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP