apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::941958612481:role/linuxtips-cluster-nodes-role
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: | # <--- SEÇÃO NOVA!
    - arn:aws:iam::941958612481:user/admin-web
      username: admin-web
      groups:
        - system:masters
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system